import { GoogleGenAI } from "@google/genai";

// IMPORTANT: Set your API key in the environment variables.
// Do not hardcode the API key in the code.
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    // In a real application, you'd want to handle this more gracefully.
    // For this example, we'll log an error to the console.
    console.error("API_KEY environment variable is not set. Please set it to use the Gemini API.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

const stylePrompts: { [key: string]: string } = {
  'Studio Portrait Photo': 'A professional studio portrait with controlled lighting. Use a three-point lighting setup (key, fill, and back light) to create depth. The background should be a solid, neutral color. The subject should be in sharp focus with a shallow depth of field (e.g., f/2.8). High-resolution, crisp details.',
  'Cinematic Film Still': 'A cinematic film still with dramatic, moody lighting and high contrast (chiaroscuro). The color grading should be distinct, like teal and orange. Add a slight film grain and a widescreen aspect ratio feel. Look for anamorphic lens flares if appropriate.',
  'Action Shot Photo': 'A dynamic action shot, captured with a fast shutter speed to freeze motion. The image should convey movement and energy. Use motion blur on the background to emphasize the subject. The lighting should be dramatic and highlight the action.',
  'Golden Hour Portrait': 'A portrait taken during the golden hour (just after sunrise or before sunset). The lighting should be soft, warm, and directional, creating long shadows and a warm glow on the subject. A beautiful, natural bokeh effect in the background is desired.',
  'Fashion Magazine Shot': 'A high-fashion shot, styled like a page from a magazine. Posing should be deliberate and artistic. Lighting should be bold and creative, possibly using colored gels or hard light for dramatic effect. The composition should be strong and editorial.',
  'Candid Photo': 'A candid, unposed shot that looks natural and spontaneous. Use natural lighting. The setting should feel authentic, like a street scene or a cafe. The focus should be on capturing a genuine moment or emotion.',
  'Black and White Photo': 'A classic black and white photograph. Emphasize contrast, texture, and form. The lighting should create strong highlights and deep shadows to define the subject. The mood can range from dramatic to nostalgic.',
  'Documentary Style Photo': 'An authentic, documentary-style photo that tells a story. Use available light. The composition should be observational and unobtrusive, capturing the subject in their natural environment without staging. Focus on realism and narrative.',
};

const layoutPrompts: { [key: string]: string } = {
  '4-panel grid': 'A 4-panel grid. Each panel must feature a distinct and unique shot of the character: 1. Full body shot. 2. Close-up portrait. 3. Action pose. 4. Character wearing an alternate costume or expressing a different emotion.',
  '6-panel grid': 'A 6-panel grid. Each panel must feature a distinct and unique shot of the character, showcasing different angles, costumes, or actions. Examples: 1. Front view. 2. Back view. 3. Side profile. 4. Action pose. 5. Close-up on face. 6. Wearing a casual outfit.',
  'T-pose reference sheet': 'A character reference sheet with the character in a T-pose, showing clear front and back views for 3D modeling reference.',
};


export const generateImageFromPrompt = async (
  characterDescription: string,
  style: string,
  layout: string,
  aspectRatio: string
): Promise<string> => {
  if (!API_KEY) {
    return Promise.reject("API Key is not configured.");
  }

  const layoutInstruction = layoutPrompts[layout] || '';
  const styleInstruction = stylePrompts[style] || `A ${style}.`;

  const finalPrompt = `
    Create a photorealistic character reference sheet.
    **Character Description:** ${characterDescription}.
    **Style:** ${styleInstruction}
    **Layout:** ${layoutInstruction}
    Ensure the character is consistent across all panels/views. The background should be a solid, neutral color (e.g., light gray) unless the style dictates otherwise. High-resolution, professional photography, photorealistic detail.
  `;

  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: finalPrompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9",
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
        return Promise.reject(`Failed to generate image: ${error.message}`);
    }
    return Promise.reject("An unknown error occurred during image generation.");
  }
};